# Configuration of the CI pipeline
name: 'External worker'
canonical: 'stack-external-worker'
description: 'This stack will deploy an Amazon ASG with external workers for Cycloid.io'
status: 'public'
keywords:
  - 'workers'
  - 'worker'
  - 'concourse'
  - 'external'
  - 'cycloid'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-external-worker/master/icon.png'
type: 'stack'
technologies:
  - technology: Amazon Auto Scaling Group
    version: n/a
  - technology: concourse
    version: 4.2.3
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/external-worker.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    external-worker:
      path: 'terraform/external-worker.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/external-worker.tf'

  ansible:
    external-worker:
      path: 'ansible/variables.yml.sample'
      destination: '($ project $)/ansible/($ environment $)-worker.yml'
